SELECT ID, NOMBRE, SALARIO
FROM IBMUSER.LAB06EMP
WHERE SALARIO =
      (SELECT MAX(SALARIO)
       FROM IBMUSER.LAB06EMP
       WHERE SALARIO <
             (SELECT MAX(SALARIO)
              FROM IBMUSER.LAB06EMP));
