SELECT A.ID,
       A.NOMBRE,
       A.SALARIO,
       (SELECT COUNT(*)
          FROM IBMUSER.LAB06EMP B
         WHERE B.SALARIO > A.SALARIO) AS SUPERIORES
FROM IBMUSER.LAB06EMP A
ORDER BY A.SALARIO DESC;
