-- Discovery (read only)
SELECT NAME, DBNAME, BPOOL
FROM SYSIBM.SYSTABLESPACE
WHERE DBNAME <> 'DSNDB06'
FETCH FIRST 20 ROWS ONLY;

SELECT CREATOR, NAME, DBNAME, TSNAME
FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'IBMUSER'
FETCH FIRST 20 ROWS ONLY;

-- Practice table
CREATE TABLE IBMUSER.LAB02
(
    ID         INTEGER      NOT NULL,
    CODIGO     CHAR(5)      NOT NULL,
    NOMBRE     VARCHAR(30),
    EDAD       SMALLINT,
    SALARIO    DECIMAL(9,2),
    FECHA_ALTA DATE,
    HORA_ALTA  TIME
);

-- Rows actually used in the practical evidence
INSERT INTO IBMUSER.LAB02
(ID, CODIGO, NOMBRE, EDAD, SALARIO, FECHA_ALTA, HORA_ALTA)
VALUES
(1, 'A0001', 'ANA', 31, 2450.50, '2026-08-23', '09:15:00');

INSERT INTO IBMUSER.LAB02
(ID, CODIGO, NOMBRE, EDAD, SALARIO, FECHA_ALTA, HORA_ALTA)
VALUES
(2, 'B0002', 'DAVID', 27, 1980.75, '2026-08-22', '14:30:00');

INSERT INTO IBMUSER.LAB02
(ID, CODIGO, NOMBRE, EDAD, SALARIO, FECHA_ALTA, HORA_ALTA)
VALUES
(3, 'C0003', 'HECTOR', 43, 3125.00, '2026-08-20', '07:45:00');

SELECT *
FROM IBMUSER.LAB02
ORDER BY ID;
