SELECT NAME, COLNO, COLTYPE, LENGTH
FROM SYSIBM.SYSCOLUMNS
WHERE TBNAME = 'SYSTABLESPACE'
  AND TBCREATOR = 'SYSIBM'
ORDER BY COLNO;

SELECT NAME, DBNAME, DBID, PSID, BPOOL
FROM SYSIBM.SYSTABLESPACE
FETCH FIRST 20 ROWS ONLY;

SELECT CREATOR, NAME, DBNAME, TSNAME
FROM SYSIBM.SYSTABLES
WHERE DBNAME = 'DSNDB06'
FETCH FIRST 20 ROWS ONLY;

SELECT NAME, COLNO, COLTYPE, LENGTH
FROM SYSIBM.SYSCOLUMNS
WHERE TBNAME = 'SYSTABLES'
  AND TBCREATOR = 'SYSIBM'
ORDER BY COLNO;

SELECT CREATOR, NAME, TBNAME, TBCREATOR
FROM SYSIBM.SYSINDEXES
WHERE TBCREATOR = 'SYSIBM'
FETCH FIRST 20 ROWS ONLY;
